services:
  - type: web
    name: btcpay
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./contrib/Dockerfile.render
    envVars:
      - key: BTCPAY_DOCKER_COMPOSE
        value: "docker-compose.generated.yml"
